# Generated by Django 4.2.2 on 2023-06-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_date_of_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_of_order',)},
        ),
    ]
