# Generated by Django 4.2.2 on 2023-06-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_destination',
            field=models.TextField(default='Kerala', max_length=100),
            preserve_default=False,
        ),
    ]
